apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-sample2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-sample2
    app.kubernetes.io/part-of: application-sample
  name: component-sample2
  namespace: maysun
spec:
  rules:
  - host: component-sample2-maysun.example.domain.com
    http:
      paths:
      - backend:
          service:
            name: component-sample2
            port:
              number: 1111
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
